### ISSUE TITLE
Navigation broken when collapsed to icon

### ISSUE THREAD

**Issue by michaeltwofish** [habari/hpo#3]
When the navigation collapses to an icon on small screens or at the smallest media query width, clicking it does not reveal the navigation.

**Comment by chrisjdavis** [comment]
Yeah, working on that as we speak.

**Comment by chrisjdavis** [comment]
I believe this is fixed now, yes?

**Comment by chrismeller** [comment]
It definitely works on my iPhone, though it causes an odd-seeming "zoom out" effect that screws up a bit of the background behind the "Modern", etc. icons and displays everything a little smaller than seems necessary (particularly for fat fingers on a phone).

Not sure if that was intentional or not...

**Comment by michaeltwofish** [comment]
It "works", but I agree with @chrismeller; the menu items are too small and the zooming a little odd.
