### ISSUE TITLE
Need search for addons

### ISSUE THREAD

**Issue by ringmaster** [habari/hpo#8]
There's no search field for addons yet, which is the big problem with habari-extras at the moment.

**Comment by Konzertheld** [comment]
Default Habari search does a fulltext search on post titles and content, right? So we would modify it to search the version term info, too? Or do we add help and description to the post content? That would propably be enough for the beginning.

What we should definitely search are tags, as soon as we have some. They are the biggest pool of keywords people are looking for but would otherwise not get hits for.

**Comment by chrisjdavis** [comment]
There is now a search, but it doesn't search any special fields. I am going to close this and open an enhancement issue for adding search of tags, etc.
